package $Storageservice.deviceImplPackageName$;

import framework.*;

public class Android$Storageservice.name$ implements I$Storageservice.name$ {

     public Android$Storageservice.name$() {
  
      }

  $Storageservice.allDataAccess:{ dataAccess |    
  
  @Override
  public $dataAccess.generatedInfo.type$ get$dataAccess.dataAccessName$($dataAccess.query.type; format="capital" $ index){
    // Use this function, when  storage is considered as 
    // sensor - It allows to reterive stored data.
     return null;
  } 
}$

$Storageservice.allActions:{ action | public  void $action.name$($action.allParameter:{ param | $param.type$ arg }; 
separator=", "$){

  }

}; separator="\n"$

}



