package $Storageservice.packageName$;

public interface  I$Storageservice.name$   {  
  
   
  $Storageservice.allDataAccess:{ dataAccess | 
  
    
  
  public void set$dataAccess.dataAccessName; format="capital"$ 
      ($dataAccess.query.type; format="capital" $ newIndex  , $dataAccess.generatedInfo.type$  new$dataAccess.dataAccessName; format="capital"$Value ); 
  
  public $dataAccess.generatedInfo.type$ get$dataAccess.dataAccessName$($dataAccess.query.type; format="capital" $ index); 
  
  
}$

  

}
    