package $Storageservice.deviceImplPackageName$;

import framework.*;

public class Android$Storageservice.name$ implements I$Storageservice.name$ {

     public AndroidProfileDB() {
  
      }

  $Storageservice.allDataAccess:{ dataAccess |    
  
  @Override
  public void set$dataAccess.dataAccessName; format="avoidCapital"$ 
      ($dataAccess.query.type; format="capital" $ newIndex, $dataAccess.generatedInfo.type$  new$dataAccess.dataAccessName; format="capital"$Value ) {
    // Use this function, when storage is considered  
  //  as an actuator - It stores data from various sources. 
    } 
 
  @Override
  public $dataAccess.generatedInfo.type$ get$dataAccess.dataAccessName$($dataAccess.query.type; format="capital" $ index){
    // Use this function, when  storage is considered as 
    // sensor - It allows to reterive stored data.
     return null;
  } 
}$

}



