package $Storageservice.deviceImplPackageName$;

import framework.*;

public class JavaSE$Storageservice.name$ implements I$Storageservice.name$ {

  public JavaSEProfileDB() {
  
  }

  $Storageservice.allDataAccess:{ dataAccess |    
  
  @Override
  public void set$dataAccess.dataAccessName; format="capital"$ 
      ($dataAccess.query.type.name; format="capital" $ newIndex, $dataAccess.generatedInfo.type.name$  new$dataAccess.dataAccessName; format="capital"$Value ) {
    // Use this function, when storage is considered  
	//  as an actuator - It stores data from various sources. 
    } 
 
  @Override
  public $dataAccess.generatedInfo.type.name$ get$dataAccess.dataAccessName$($dataAccess.query.type.name; format="capital" $ index){
    // Use this function, when  storage is considered as 
	  // sensor - It allows to reterive stored data.
     return null;
  } 
}$

}



