package $SensorDriver.deviceImplPackageName$;

import framework.*;






public class JavaSE$SensorDriver.name$ implements I$SensorDriver.name$ {

	// TODO : Developer will configure the following appropriately.
			private boolean badgeDetectedCondition = false;
			private boolean badgeDisappearedCondition = false;
   
   /*public JavaSE$SensorDriver.name$() { 
  
  
  }*/
	
  
   $SensorDriver.allGeneratedInfo:{ generatedInfo | 
   
  /* @Override
   public  $generatedInfo.type.name$ get$generatedInfo.name; format="avoidCapital"$(){
		   return null;
   }*/
	  
	  
      
   @Override
   public void get$generatedInfo.name; format="avoidCapital"$(Listener$generatedInfo.name$ handler){
	// continueFlag = true;
      
   }   
      
}; separator="\n"$
  
  @Override
  public boolean isEventDriven() {
    return true;
  }

}
