package $Actuatordriver.factoryDeviceImplActuator$;

import framework.*;


public class JavaSE$Actuatordriver.name$ implements I$Actuatordriver.name$ {


  public JavaSE$Actuatordriver.name$() {
  
  
  
  }

  $Actuatordriver.allActions:{ action |   
  
  @Override
  public void $action.name$($action.allParameter:{ param | $param.type.name$ arg }; 
   separator=", "$) {
   
   } 
    
   }; separator="\n"$ 
 
}


