package $Storageservice.packageName$;

public interface  I$Storageservice.name$   {  
  
   
  $Storageservice.allDataAccess:{ dataAccess |     
  
   public $dataAccess.generatedInfo.type$ get$dataAccess.dataAccessName$($dataAccess.query.type; format="capital" $ index); 
  
  
}$

$Storageservice.allActions:{ action | public abstract void $action.name$($action.allParameter:{ param | $param.type$ arg }; 
separator=", "$); 

}; separator="\n"$

  

}
    