package $CS.logicPackageName$;
import fr.inria.arles.pankesh.pubsubmiddleware.PubSubMiddleware;
import android.content.Context;
import fr.inria.arles.pankesh.semanticmodel.*;
import $CS.PackageName$.*;



public class Logic$CS.name$ extends $CS.name$ {

	public Fake$CS.name$(PubSubMiddleware pubSubM, Device deviceInfo, Object ui,Context myContext) {
		super(pubSubM, deviceInfo);
	}
	
	$CS.allConsumedInfo:{ consumedInfo | 	   
	    public void onNew$consumedInfo.name; format="avoidCapital"$( $consumedInfo.type.name$ arg)
	    {
	    	//TODO : write code here 
	    }	   	
	}$	
	
		
	

}