package $Actuatordriver.factoryDeviceImplActuator$;

import framework.*;
import android.content.Context;
import logic.*;
import android.os.Bundle;
import android.app.Dialog;

/* Rename class-name with Implementation.   */

public class Android$Actuatordriver.name$ extends Dialog implements I$Actuatordriver.name$ {

     private Context myContext;
  
   public Android$Actuatordriver.name$(Context context, Logic$Actuatordriver.name$  obj) {
		super(context);
		this.myContext = context;
		//this.fn = (Fake$Actuatordriver.name$) obj;
	}
	
	public void onCreate(Bundle savedInstanceState) {

		//setContentView(R.layout.activity_main);
		super.onCreate(savedInstanceState);

	
	}
    

   

  $Actuatordriver.allActions:{ action |   
  
  @Override
  public void $action.name$($action.allParameter:{ param | $param.type.name$ arg }; 
   separator=", "$) {
   
   } 
    
   }; separator="\n"$ 
 
}


