package $Storageservice.deviceImplPackageName$;

import framework.*;

/* Rename class-name with Implementation.   */
public class Impl$Storageservice.name$ implements I$Storageservice.name$ {

  $Storageservice.allDataAccess:{ dataAccess |    
  
  @Override
  public void set$dataAccess.dataAccessName; format="capital"$ 
      ($dataAccess.query.type.name; format="capital" $ newIndex, $dataAccess.generatedInfo.type.name$  new$dataAccess.dataAccessName; format="capital"$Value ) {
      
      } 
  
  @Override
  public $dataAccess.generatedInfo.type.name$ get$dataAccess.dataAccessName$($dataAccess.query.type.name; format="capital" $ index){
  
  return null;
  } 
 
  
}$

	@Override
	public boolean isEventDriven() {
	
	return false;	
	}


}



