package $SensorDriver.deviceImplPackageName$;

import framework.*;



public class JavaSE$SensorDriver.name$ implements I$SensorDriver.name$ {

   



  
   $SensorDriver.allGeneratedInfo:{ generatedInfo | 
   
  /* @Override
   public  $generatedInfo.type.name$ get$generatedInfo.name; format="avoidCapital"$(){
		   return null;
   }*/
      
   @Override
   public void get$generatedInfo.name; format="avoidCapital"$(Listener$generatedInfo.name$ handler){
   
   }   
      
}; separator="\n"$
  
  @Override
  public boolean isEventDriven() {
    return true;
  }

}
