package $SensorDriver.packageName$;


public abstract interface  I$SensorDriver.name$ { 
   
  
  $SensorDriver.allGeneratedInfo:{ generatedInfo | 
   
   public abstract   $generatedInfo.type.name$ get$generatedInfo.name; format="avoidCapital"$();
   
   public abstract void get$generatedInfo.name; format="avoidCapital"$(Listener$generatedInfo.name$ handler);
  
   
        
      
}; separator="\n"$


   public abstract boolean isEventDriven(); 
   
}