package $Storageservice.packageName$;

public interface  I$Storageservice.name$   {  
  
   
  $Storageservice.allDataAccess:{ dataAccess | 
  
    
  
  public void set$dataAccess.dataAccessName; format="capital"$ 
      ($dataAccess.query.type.name; format="capital" $ newIndex  , $dataAccess.generatedInfo.type.name$  new$dataAccess.dataAccessName; format="capital"$Value ); 
  
  public $dataAccess.generatedInfo.type.name$ get$dataAccess.dataAccessName$($dataAccess.query.type.name; format="capital" $ index); 
  
  
}$

  public abstract boolean isEventDriven();   

}
    